apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cassandrabackups.cassandraoperator.instaclustr.com
spec:
  group: cassandraoperator.instaclustr.com
  names:
    kind: CassandraBackup
    listKind: CassandraBackupList
    plural: cassandrabackups
    singular: cassandrabackup
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            destinationUri:
              description: The uri for the backup target location e.g. s3 bucket,
                filepath
              type: string
            keyspaces:
              description: The list of keyspaces to back up
              items:
                type: string
              type: array
            snapshotName:
              type: string
            type:
              description: The backup mechanism type e.g. S3, FILE
              type: string
          required:
          - type
          - destinationUri
          - keyspaces
          - snapshotName
          type: object
        status:
          properties:
            progress:
              description: Progress shows the status of the operation
              type: string
          required:
          - progress
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
