apiVersion: cassandraoperator.instaclustr.com/v1alpha1
kind: CassandraDataCenter
metadata:
  name: test-dc-cassandra
  labels:
    app: cassandra
spec:
  cluster: "test-cluster"
  nodes: 3
  racks: 3
  cassandraImage: "gcr.io/cassandra-operator/cassandra:3.11.3"
  sidecarImage: "gcr.io/cassandra-operator/cassandra-sidecar:latest"
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - name: regcred
  backupSecretVolume:
    secretName: backup-secret
    #     type is a workaround for https://github.com/kubernetes/kubernetes/issues/68466
    type: array
    items:
      - key: creds.json
        path: creds.json
  env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: "/etc/google/creds.json"
  userConfigMapVolumeSource:
    name: concurrent-data
    #     type is a workaround for https://github.com/kubernetes/kubernetes/issues/68466
    type: array
    items:
      - key: "concurrent.yaml"
        path: "cassandra.yaml.d/100-user.yaml"
  resources:
    limits:
      memory: 1Gi
    requests:
      memory: 1Gi

  dataVolumeClaimSpec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 500Mi

  prometheusSupport: false
  privilegedSupported: true
