apiVersion: cassandraoperator.instaclustr.com/v1alpha1
kind: CassandraBackup
metadata:
  name: test-cassandra-backup
  labels:
    app: cassandra
spec:
  cdc: test-dc-cassandra
  destinationUri: "s3://instaclustr_k8/tmp/2"
  snapshotName: "alex2"
  keyspaces: ["alex1", "alex2"]
