apiVersion: v1
entries:
  cassandra:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2019-10-04T14:29:07.88860552+09:30"
    description: A Helm chart for creating Cassandra clusters using the Cassandra
      operator
    digest: 3d33b4744768d533bfb992f2332ce7a85a225554ec155061c30ebb1f60c06ed3
    home: https://www.instaclustr.com
    keywords:
    - operator
    - cassandra-operator
    - instaclustr
    maintainers:
    - name: Stefan Miklosovic
    - name: Alex Lourie
    - name: Ben Bromhead
    - name: Adam Zegelin
    name: cassandra
    sources:
    - https://github.com/instaclustr/cassandra-operator
    urls:
    - cassandra-0.1.0.tgz
    version: 0.1.0
  cassandra-operator:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2019-10-04T14:29:07.889076693+09:30"
    description: A Helm chart for Cassandra Operator for Kubernetes by Instaclustr
    digest: 39d2f8f2bb61ab710154f1ae2558574da8226c1729fc6f387c6feea8e227d1ba
    home: https://www.instaclustr.com
    keywords:
    - operator
    - cassandra-operator
    - instaclustr
    maintainers:
    - name: Stefan Miklosovic
    - name: Alex Lourie
    - name: Ben Bromhead
    - name: Adam Zegelin
    name: cassandra-operator
    sources:
    - https://github.com/instaclustr/cassandra-operator
    urls:
    - cassandra-operator-0.1.0.tgz
    version: 0.1.0
generated: "2019-10-04T14:29:07.888107843+09:30"
