apiVersion: v1
entries:
  cassandra:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2019-09-24T10:45:09.396031658+09:30"
    description: A Helm chart for creating Cassandra clusters using the Cassandra
      operator
    digest: 4a241ae1ef5e5bcd88af8cd50047ad51d23e2f1b223b9b2caad0b8c1c49c5646
    home: https://www.instaclustr.com
    keywords:
    - operator
    - cassandra-operator
    - instaclustr
    maintainers:
    - name: Stefan Miklosovic
    - name: Alex Lourie
    - name: Ben Bromhead
    - name: Adam Zegelin
    name: cassandra
    sources:
    - https://github.com/instaclustr/cassandra-operator
    urls:
    - cassandra-0.1.0.tgz
    version: 0.1.0
  cassandra-operator:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2019-09-24T10:45:09.396532714+09:30"
    description: A Helm chart for Cassandra Operator for Kubernetes by Instaclustr
    digest: be5ce2bfc8d5fd6c42c1413b31b50919e7a29e75408eb8184ab393bc08dcbdb7
    home: https://www.instaclustr.com
    keywords:
    - operator
    - cassandra-operator
    - instaclustr
    maintainers:
    - name: Stefan Miklosovic
    - name: Alex Lourie
    - name: Ben Bromhead
    - name: Adam Zegelin
    name: cassandra-operator
    sources:
    - https://github.com/instaclustr/cassandra-operator
    urls:
    - cassandra-operator-0.1.0.tgz
    version: 0.1.0
generated: "2019-09-24T10:45:09.395461266+09:30"
